language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -i -S
after_success:
  - ./gradlew uploadJars -S -i
  - ./gradlew createGithubBranches -S